- .eleventy.js
- .github/workflows/build-and-deploy-main.yml
- cypress/e2e/spec.cy.js
Squashed commits:
[fc6a9ac] Add process env to fix sub directory includes. Added e2e test to make sure the principles page loads.
> Update action workflow to inject new prefix. (+1 squashed commits)

- _includes/macros/tags.njk
- docs/tags-list.md
- docs/tags.md
Updated tag page's permalink to be slugified, fixing issues with multi-word tags.
Updated other references to tag URLs to not title case the URL, this is no longer needed.
> Updated tag page's permalink to be slugified, fixing issues with multi-word tags.

- .eleventy.js
- LICENCE
- docs/standards/open-source-licensing.md
Drafted as reformat of previous guidance included in internal documentation
This will close #84
> Create open source licensing standard

- package-lock.json
> Updates x-govuk/govuk-eleventy-plugin to 5.0.1

- docs/principles/design-for-success.md
> Create the design for success principle

- docs/principles/be-collaborative.md
Initial draft of principle from existing internal content, and output from Software Design guild sessions
This will close #124
> Create 'Be collaborative' principle

- .eleventy.js
- cypress/e2e/spec.cy.js
- docs/index.md
I can confirm:
or
or
I can confirm:
> Fix startButton and footer links to about page

- .eleventyignore
- CONTRIBUTING.md
- Added details of build, release, deploy and updated PR instructions to CONTRIBUTING.md
- Added CONTRIBUTING.md to Eleventy ignore file (avoids needing `eleventyExcludeFromCollections` in the MD file which appears at the top of the page when viewing on GitHub).
I can confirm:
or
or
- [] This change might impact accessibility and is not covered by automated aXe tests - manual testing has been performed
I can confirm:
_Configuration change added to ignore CONTRIBUTING.md from Eleventy page generation only._
e.g. [Writing a principle](https://ho-cto.github.io/engineering-guidance-and-standards/docs/standards/writing-a-principle/) and [Writing a …
> Updated CONTRIBUTING.md

- docs/principles/well-managed-code.md
> Create well-managed-code.md principle

- .github/workflows/build-and-deploy-main.yml
- .github/workflows/e2e-tests-on-pr.yml
Using setup-node with specified node version.
I can confirm:
> Using setup-node action for build-deploy and e2e tests

- docs/principles/improve-engineering-experience.md
- docs/principles/provide-good-engineering-experience.md
> Create 'Provide a good engineering experience' principle

- _includes/layouts/pattern.njk
- _includes/layouts/principle.njk
- _includes/macros/navigationList.njk
Will close #208 and #206 
I can confirm:
- [ x] This change might impact accessibility, automated aXe tests cover the impact
> Fixed menu item population in layouts and added url filter to links in navigation macro

- .eleventyignore
- CONTRIBUTING.md
- docs/patterns/pattern.template.md
- docs/principles/principle.template.md
- docs/standards/standard.template.md
- docs/standards/writing-a-principle.md
- docs/standards/writing-a-standard.md
> Added templates for new patterns, principles, and standards

- docs/principles/monitor-and-measure.md
Will close #83 
I can confirm:
> Create 'monitor and measure proactively' principle

- docs/patterns/immutable-artefacts.md
> Create 'immutable artefacts' pattern

- docs/patterns/docs-as-code.md
I can confirm:
Will close #146
> Create 'docs as code' pattern

- docs/principles/end-to-end-product-ownership.md
Will close #112 
I can confirm:
> Create 'end to end product ownership' principle

- docs/standards/managing-secrets.md
Will close #197 
I can confirm:
> Create 'Managing secrets' standard

- docs/principles/design-from-evidence.md
Will close #113 
I can confirm:
> Create 'Design from evidence' principle

- .eleventy.js
- _data/eleventyComputed.js
- _includes/layouts/collection.njk
- cypress/e2e/spec.cy.js
> Added handlers to allow pagination links to include path prefix

- _includes/layouts/search-index.njk
I can confirm:
- [/] This change will not change layouts, page structures or anything else that might impact accessibility
or
or
I can confirm:
> 212 Improve site search so that can search by standard id contentid

- docs/patterns/application-logging-security.md
- docs/patterns/securing-application-logging.md
Will close #226 
I can confirm:
> Create 'Securing application logging' pattern

- package-lock.json
I can confirm:
or
or
I can confirm:
> Chore: Update vulnerable deps

- docs/standards/accessibility.md
Will close #241 
I can confirm:
> Create 'Accessibility' standard

- docs/patterns/catch-defects-early.md
- docs/patterns/catch-problems-early.md
Will close #244 
I can confirm:
> Add Catch problems early (shift left) pattern

- .eleventy.js
- docs/provide-feedback.md
Will close #263 
I can confirm:
> Change feedback link to intermediary page with links to GitHub issues and email

- docs/patterns/threat-modelling.md
- docs/principles/proportionate-security.md
Will close #255 
I can confirm:
> Create 'threat modelling' pattern

- docs/standards/encrypting-data-rest-transit.md
Will close #253 
I can confirm:
> Create 'Encrypting data at rest and in transit' standard

- docs/standards/infrastructure-utilisation-monitoring.md
Will close #260 
I can confirm:
> Create 'infrastructure utilisation monitoring' standard

- .eleventy.js
- .github/ISSUE_TEMPLATE/propose-a-new-principle.md
- .github/ISSUE_TEMPLATE/propose-a-new-standard.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
- docs/about.md
- docs/accessibility-statement.md
- docs/provide-feedback.md
- docs/standards/open-source-licensing.md
- docs/standards/writing-a-principle.md
- docs/standards/writing-a-standard.md
> 286 replace existing links to the GitHub repository and files

- .github/ISSUE_TEMPLATE/review-content.md
Will close #313 
I can confirm:
I can confirm:
e.g. [Writing a principle](https://engineering.homeoffice.gov.uk/standards/writing-a-principle/) and [Writing a standard](https://engineering.homeoffice.gov.uk/standards/writing-a-standard/)
> Update review-content.md issue template to make purpose clearer

- docs/about.md
This will close #302 
I can confirm:
e.g. [Writing a principle](https://engineering.homeoffice.gov.uk/standards/writing-a-principle/) and [Writing a standard](https://engineering.homeoffice.gov.uk/standards/writing-a-standard/)
> Updated roadmap in about.md

- docs/accessibility-statement.md
- technical-docs/accessibility/layout-checks.md
I can confirm:
e.g. [Writing a principle](https://engineering.homeoffice.gov.uk/standards/writing-a-principle/) and [Writing a standard](https://engineering.homeoffice.gov.uk/standards/writing-a-standard/)
> 307 update accessibility statement following feedback from ho access team
