- cypress/e2e/spec.cy.js
- docs/tags.md
Updated links in tags page to use "url" filter, ensuring they respect the path prefix
Added cypress tests that check the "all tag" and links from the list of pages using a tag page
> Fix for broken tag page links; updated links in tags page to use "url" filter

- docs/patterns/monitoring-as-code.md
Initial draft of pattern that gives high-level description of what MaC is and where to find it
> Create Monitoring-as-code (MaC) pattern

- .eleventy.js
- _includes/layouts/base.njk
- _includes/layouts/collection.njk
- _includes/layouts/page.njk
- _includes/layouts/post.njk
- _includes/layouts/product.njk
- _includes/layouts/search-index.njk
- _includes/layouts/shared/related.njk
- _includes/layouts/sitemap.njk
- _includes/layouts/sub-navigation.njk
- _includes/layouts/tag.njk
- _includes/layouts/tags.njk
- _includes/macros/feedbackBanner.njk
- styles/base.scss
- added alpha banner with link to feedback survey
- implemented by overriding all layouts and adding the banner to each template
- considered overriding `base.njk` layout, however, all other layouts would have to be implemented fully. Therefore consider proposed solution preferable.
> Addition of alpha banner with link to feedback survey

- docs/standards/minimal-documentation-set-for-a-product.md
Fixes two issues with formatting on the minimal documentation set standard:
- errant new line on summary
- typo in link
> Fix: Minimal documentation set formatting issues

- .eleventy.js
I have used ["Footer with links"](https://design-system.service.gov.uk/components/footer/) for the addition of the GitHub repo link.
Please see below for preview of updated UI.
> Added link to GitHub repository in footer

- docs/principles/collaborative-open-working.md
- docs/principles/work-in-the-open.md
Content migration from internal docs with rewrite to bring in line with 'writing a principle' standard, and flesh out main sections.
This will close #97
> Create 'work in the open' principle

- docs/about.md
Removing about link from eleventy collections, which prevents the page appearing in the sidebar on pages that use the sub-navigation layout
I can confirm:
or
or
> Excluded about page from eleventy collections

- .eleventy.js
- .github/workflows/e2e-tests-on-pr.yml
- _data/eleventyComputed.js
- cypress/e2e/a11y.spec.cy.js
- cypress/e2e/spec.cy.js
- cypress/support/testing_params.js
- docs/patterns/pattern.template.md
- docs/principles/principle.template.md
- docs/standards.md
- docs/standards/standard.template.md
Replaces or compliments #210 - adds mapping for related links frontmatter to include pathPrefix so that absolute links work.
Updates Cypress tests to support a path prefix so that this can be tested in the GitHub action test run.
I can confirm:
> Fix for #209 - support path prefix in related links

- .github/PULL_REQUEST_TEMPLATE.md
- docs/patterns/docs-as-code.md
- docs/patterns/immutable-artefacts.md
- docs/patterns/monitoring-as-code.md
- docs/patterns/pattern.template.md
- docs/patterns/selecting-a-deployment-strategy.md
- docs/patterns/write-effective-documentation.md
- docs/principles/be-collaborative.md
- docs/principles/design-for-success.md
- docs/principles/monitor-and-measure.md
- docs/principles/principle.template.md
- docs/principles/proportionate-security.md
- docs/principles/provide-good-engineering-experience.md
- docs/principles/security-is-everyones-responsibility.md
- docs/principles/well-managed-code.md
- docs/principles/work-in-the-open.md
- docs/principles/write-maintainable-reusable-and-evolutionary-code.md
- docs/principles/zero-trust.md
- docs/standards/infrastructure-as-code.md
- docs/standards/minimal-documentation-set-for-a-product.md
- docs/standards/open-source-licensing.md
- docs/standards/standard.template.md
- docs/standards/writing-a-principle.md
- docs/standards/writing-a-standard.md
- Updated all content pages to use the explicit last updated date rather than `git Last Modified`
- Updated writing a principle/standard to reflect changes on usage of last updated date
- Added step for PR template to confirm last updated dates are updated
I can confirm:
I can confirm:
> Updated last updated dates for content pages - removed usage of git Last Modified

- .eleventy.js
- docs/patterns/docs-as-code.md
- lib/markdown/dl-as-govuk-summary-list.js
- Migrate docs-as-code pattern to use `dl`s for technical summaries of docs-as-code frameworks
Is this pull request a content or a code change? Code change with content presenntation change
I can confirm:
I can confirm:
> Use govuk summary list for docs-as-code technology options

- .eleventy.js
- _includes/layouts/tag.njk
- _includes/layouts/tags.njk
- cypress/e2e/a11y.spec.cy.js
- docs/tags-list.md
- docs/tags.md
- Using tag/tags layouts for tags page and all tags page, respectively.
- Updated layouts to use standard content listing and to display three main content links (to match other pages)
I can confirm:
> Update tag pages to match other content listing pages

- docs/standards/managing-dependencies.md
- docs/standards/managing-security-software-dependencies.md
Will close #238 
I can confirm:
> Create 'Managing the security of software dependencies' standard

- .github/workflows/build-and-deploy-main.yml
> Removed trailing forward slash from PATH_PREFIX

- cypress/e2e/spec.cy.js
- docs/standards.md
Removed related link from standards page.
Intent is to reinstate when site is migrated to ACP and we do not have issues with usage of `pathPrefix`
I can confirm:
> Removed related links from standards page

- .eleventy.js
- .github/ISSUE_TEMPLATE/report_an_accessibility_issue.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build-and-deploy-main.yml
- cypress/e2e/a11y.spec.cy.js
- docs/about.md
- docs/accessibility-statement.md
- docs/provide-feedback.md
- technical-docs/accessibility/content-checks.md
- technical-docs/accessibility/layout-checks.md
> Add accessibility checklists

- helm/values.yaml
Links to #213 
Enable the external ingress to allow for the `engineering.homeoffice.gov.uk` domain.
I can confirm:
> Enable external ingress

- helm/templates/ingress-external.yaml
As the DNS zone hasn't been delegated for the domain, the route53 solver cannot be used. This change removes this, falling back to the default.
I can confirm:
> Remove solver for external ingress

- helm/templates/ingress-external.yaml
While our hosting platform defaults to `http01` solver when the label isn't specified. It is still required by the schema when the cert-manager is enabled. This change adds this explicitly in.
I can confirm:
> Explicitly specify cert-manager solver

- docs/standards/minimal-documentation-set-for-a-product.md
Will close #314 
I can confirm:
e.g. [Writing a principle](https://engineering.homeoffice.gov.uk/standards/writing-a-principle/) and [Writing a standard](https://engineering.homeoffice.gov.uk/standards/writing-a-standard/)
> SEGAS-00003: Added line to require naming SRO in product documentation

- Dockerfile
The SITE_ROOT env variable needs to be set to the expected root of the site when the static pages are being built by 11ty.
I can confirm:
> Set site root when building docker container

- .eleventy.js
- .github/workflows/e2e-tests-on-pr.yml
- _data/eleventyComputed.js
- _includes/layouts/collection.njk
- _includes/layouts/tags.njk
- cypress/e2e/spec.cy.js
Removed tech debt related to path prefix usages.
Path prefix is no longer required due to the site being hosted at the root of the engineering.homeoffice.gov.uk domain
I can confirm:
> Removed tech debt related to path prefix usages

- .eleventy.js
- .github/workflows/e2e-tests-on-pr.yml
- _data/eleventyComputed.js
- _includes/layouts/collection.njk
- _includes/layouts/tags.njk
- cypress/e2e/spec.cy.js
- docs/principles.md
- docs/standards.md
Added related links for writing a principle/standard to the respective principle/standard listing page
I can confirm:
> Added related links for writing a principle/standard to the respective principle/standard listing page

- _includes/layouts/tag.njk
- _includes/macros/contentDocumentList.njk
- cypress/e2e/spec.cy.js
- docs/patterns/patterns.11tydata.js
- docs/principles/principles.11tydata.js
- docs/standards/standards.11tydata.js
Added content category for items in tag page.
See below for preview:
---
I can confirm:
> Add content category for items in tag page
